### PR TITLE
Fix --purge to remove root cache directory instead of version directory

### LINKED ISSUE #561: `--purge` removes the version directory, not the actual cache directory
The problem stems from here: https://github.com/trailofbits/cargo-unmaintained/blob/a8f16bc234399f6cb3dc672b0ecf0c9bf52ac545/src/on_disk_cache.rs#L68-L73

The version (i.e., `v2`) should be separated so that `CACHE_DIRECTORY` refers to `$HOME/.cache/cargo-unmaintained`.

Then, `purge_cache` will remove that directory rather than the version directory: https://github.com/trailofbits/cargo-unmaintained/blob/a8f16bc234399f6cb3dc672b0ecf0c9bf52ac545/src/on_disk_cache.rs#L420-L425

---

When this is fixed, the `no_cache` test should be updated as well: https://github.com/trailofbits/cargo-unmaintained/blob/a8f16bc234399f6cb3dc672b0ecf0c9bf52ac545/tests/no_cache.rs#L70-L73

### PR DESCRIPTION
**Pull request by Stereco-btc**
## Description
This PR addresses issue #561 where the `--purge` flag was only removing the version directory (`$HOME/.cache/cargo-unmaintained/v2`) instead of the entire cache directory (`$HOME/.cache/cargo-unmaintained`).

## Changes
- Refactored the `CACHE_DIRECTORY` constant to point to the base cache directory path
- Added a new `VERSION` constant to isolate the version string
- Added a `LazyLock` for `VERSION_DIR` in the `base_dir` method to properly handle versioned directory access
- Updated the `purge_cache` function and its documentation to accurately reflect that it removes the entire cache directory
- Modified the `no_cache` test to verify the root cache directory is removed, not just the version directory

## Testing
All tests have been updated and are passing, including the specific `no_cache` test which verifies the purge functionality.

## Fixes
Fixes #561

### CODE REVIEW

File: src/on_disk_cache.rs [hunk 1]
```diff
@@ -363,7 +367,21 @@ impl Cache {
         let base_dir = self.tempdir.as_ref().map(TempDir::path);
 
         #[cfg(all(feature = "on-disk-cache", not(windows)))]
-        return base_dir.unwrap_or(&CACHE_DIRECTORY);
+        {
+            static VERSION_DIR: LazyLock<PathBuf> = LazyLock::new(|| {
+                let mut path = CACHE_DIRECTORY.clone();
+                path.push(VERSION);
+                if let Err(e) = create_dir_all(&path) {
```
Comment (smoelius) [inline src/on_disk_cache.rs:374]: You must have had a reason for calling `create_dir_all` here. What is that reason?

Comment (Stereco-btc) [reply src/on_disk_cache.rs:374]: @smoelius The reason for calling create_dir_all here is to ensure the version directory exists when it's first accessed. Since I'm using LazyLock for lazy initialization of the version directory path, I need to ensure the directory is created exactly once when it's first needed. If you have any thoughts about this, please do share them.

Comment (smoelius) [reply src/on_disk_cache.rs:374]: Is there a specific failure you've observed?

I don't think that `create_dir_all` should be needed here. I think `create_dir_all` is called before any subdireoctory of `CACHE_DIRECTORY` is accessed. (Please correct me if I'm wrong.)

By chance, have you tried something like the following?
```rs
return base_dir.unwrap_or(&CACHE_DIRECTORY).join(VERSION);
```
Note that you may have to change `base_dir`'s return type.

If this does not work, I'd be curious to know why.

File: src/on_disk_cache.rs [hunk 2]
```diff
@@ -68,10 +68,14 @@ thread_local! {
...
     let base_directories = xdg::BaseDirectories::new().unwrap();
     base_directories
-        .create_cache_directory("cargo-unmaintained/v2")
+        .create_cache_directory("cargo-unmaintained")
         .unwrap()
 });
 
+#[cfg(all(feature = "on-disk-cache", not(windows)))]
+/// The current version of the cache structure
+static VERSION: &str = "v2";
```
Comment (smoelius) [inline src/on_disk_cache.rs:77]:
```suggestion
const VERSION: &str = "v2";
```

File: src/on_disk_cache.rs (hunk 1 above)
Comment (Stereco-btc) [reply src/on_disk_cache.rs]: @smoelius I've made the changes you suggested. To implement the code yo gave, I had to change the return type, also I removed the return keyword from `return base_dir.unwrap_or(&CACHE_DIRECTORY).join(VERSION);` as this was giving a clippy error, hope this fixes everything, Please take a look.

Comment (smoelius) [reply src/on_disk_cache.rs]: > also I removed the return keyword from return base_dir.unwrap_or(&CACHE_DIRECTORY).join(VERSION); as this was giving a clippy error

Can I ask what the error was?

Comment (Stereco-btc) [reply src/on_disk_cache.rs]: > error: unneeded `return` statement
   --> src/on_disk_cache.rs:371:13
    |
371 |             return base_dir.unwrap_or(&CACHE_DIRECTORY).join(VERSION)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
    = note: `-D clippy::needless-return` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::needless_return)]`
help: remove `return`
    |
371 |             base_dir.unwrap_or(&CACHE_DIRECTORY).join(VERSION)
    |

 @smoelius this was the error message, so following the suggestion I removed the return keywork and the clippy test passed.
